using BeeMemoryBank.Core.Interfaces;
using BeeMemoryBank.Core.Models;
using BeeMemoryBank.Core.Services;
using BeeMemoryBank.Storage.Sqlite;
using Dapper;
using Microsoft.Extensions.DependencyInjection;

namespace BeeMemoryBank.Core.Tests;

/// <summary>
/// A vault from before the password unification, opened by this build (docs/encryption.md,
/// "Password Unification"): one shared <c>slot_type='password'</c> row, no user pointing at a slot
/// until the first successful unlock runs <see cref="LegacyPasswordSlotMigrationService"/>.
///
/// <para>This is the 1.0.11 upgrade path, and it is not a hypothetical: the vault is intact and one
/// password away from being usable. <c>IsInitializedAsync</c> answering "not initialized" here sends
/// the operator to the setup wizard instead of the unlock prompt, so the unlock that would migrate
/// the shape never happens — the brick the reviewers found in release-a2 (agy#2, sec#5).</para>
///
/// <para>The fixtures are built rather than shipped as a binary: a modern vault is stood up and then
/// rewritten into the legacy shape by the same rules the migration service reads it by (its slot
/// type constant), with a sanity check that the rewrite really did change the shape. A vault made by
/// the real 1.0.11 binaries is verified separately in REPORT.md — a committed binary fixture would
/// age badly and cannot be regenerated by CI.</para>
/// </summary>
public class LegacyVaultUpgradeTests : IAsyncDisposable
{
    private const string Password = "legacy-vault-pass-1";
    private readonly string _root = Path.Combine(Path.GetTempPath(), "bmb-legacy-" + Guid.NewGuid().ToString("N"));
    private DbConnectionFactory? _factory;
    private readonly List<ServiceProvider> _providers = [];

    public async ValueTask DisposeAsync()
    {
        foreach (var p in _providers)
        {
            try { p.Dispose(); } catch { }
        }
        try { _factory?.Dispose(); } catch { }
        try { Directory.Delete(_root, recursive: true); } catch { }
        await ValueTask.CompletedTask;
    }

    /// <summary>
    /// A vault as this build initializes one, then rewritten into the pre-unification shape:
    /// the slot becomes the shared legacy one, no user points at a slot, and the unification marker
    /// is gone (a pre-unification vault never had one).
    /// </summary>
    private async Task<(DbConnectionFactory Factory, InitializationService Init, SessionService Session)>
        BuildLegacyVaultAsync(bool keepUsers)
    {
        // The Guid/DateTime handlers every repository read relies on (DapperConfig).
        DapperConfig.Configure();
        Directory.CreateDirectory(_root);
        var factory = new DbConnectionFactory(_root);
        _factory = factory;
        await new MigrationRunner(factory).RunMigrationsAsync();

        var keySlots = new KeySlotRepository(factory);
        var nodeRepo = new NodeIdentityRepository(factory);
        var userRepo = new UserRepository(factory);
        var init = new InitializationService(nodeRepo, keySlots, userRepo, factory, new RestoreBootstrapMarker(factory));
        await init.InitializeAsync("admin", "LegacyNode", Password);

        // Sanity: the vault this build makes is the modern shape, so what follows is a real change.
        (await init.IsInitializedAsync()).Should().BeTrue("the vault was just initialized");
        (await keySlots.GetAllAsync()).Should().ContainSingle(s => s.SlotType == "user");

        using (var conn = factory.CreateConnection())
        {
            await conn.ExecuteAsync(
                "UPDATE tbl_key_slot SET slot_type = @legacy",
                new { legacy = LegacyPasswordSlotMigrationService.LegacySlotType });
            await conn.ExecuteAsync("UPDATE tbl_user SET key_slot_id = NULL");
            await conn.ExecuteAsync("DELETE FROM tbl_migration_marker WHERE key = 'legacy_password_unified'");
            if (!keepUsers)
                await conn.ExecuteAsync("DELETE FROM tbl_user");
        }

        // The migration runs from inside UnlockAsync through the DI scope factory — the same way
        // the host wires it (SessionService's optional scopeFactory parameter) — so the test
        // exercises the real upgrade path, not a hand-called migration.
        var services = new ServiceCollection();
        services.AddSingleton<IKeySlotRepository>(keySlots);
        services.AddSingleton<IUserRepository>(userRepo);
        services.AddSingleton<IDbConnectionFactory>(factory);
        // TryDeriveAuthorizedMasterDekAsync resolves the identity (for the v=0/v=1 seed path) and
        // the retired-DEK store while it walks the slots.
        services.AddSingleton<INodeIdentityRepository>(nodeRepo);
        services.AddSingleton<IRetiredMasterDekStore>(new RetiredMasterDekStore(factory));
        services.AddTransient<LegacyPasswordSlotMigrationService>();
        var provider = services.BuildServiceProvider();
        _providers.Add(provider);

        var session = new SessionService(keySlots, provider.GetRequiredService<IServiceScopeFactory>());
        return (factory, init, session);
    }

    private async Task<List<MasterKeyStore>> SlotsAsync(DbConnectionFactory factory)
    {
        using var conn = factory.CreateConnection();
        return (await conn.QueryAsync<MasterKeyStore>(
            "SELECT slot_id AS SlotId, slot_type AS SlotType FROM tbl_key_slot")).ToList();
    }

    private async Task<List<(string Username, string Role, int? Slot)>> UsersAsync(DbConnectionFactory factory)
    {
        using var conn = factory.CreateConnection();
        var rows = await conn.QueryAsync<(string Username, string Role, int? Slot)>(
            "SELECT username AS Username, role AS Role, key_slot_id AS Slot FROM tbl_user WHERE is_active = 1");
        return rows.ToList();
    }

    [Fact]
    public async Task ALegacyVaultWhoseUsersHaveNoSlot_IsInitialized_AndUnlocksWithItsPassword()
    {
        var (factory, init, session) = await BuildLegacyVaultAsync(keepUsers: true);

        (await init.IsInitializedAsync()).Should().BeTrue(
            "the vault is intact: the operator's next stop is the unlock prompt, not the setup wizard");

        (await session.UnlockAsync(Password)).Should().BeTrue("the old password still opens the vault");
        session.IsUnlocked.Should().BeTrue();

        // The unlock ran the migration: the shared slot is promoted to a per-user one, and a
        // superadmin owns it. The migration cannot know WHOSE password opened the vault, so it
        // creates its own admin for the promoted slot; the pre-existing user stays and is
        // provisioned with a slot of their own at their next login (UserService.TryAssignKeySlotAsync),
        // which is why this asserts an owner rather than naming one.
        var slots = await SlotsAsync(factory);
        slots.Should().ContainSingle("the shared slot is promoted, not duplicated");
        slots[0].SlotType.Should().Be("user");
        var owners = (await UsersAsync(factory)).Where(u => u.Slot == slots[0].SlotId).ToList();
        owners.Should().ContainSingle("the promoted slot belongs to exactly one account");
        owners[0].Role.Should().Be("superadmin");
        (await UsersAsync(factory)).Should().Contain(u => u.Username == "admin",
            "the pre-existing user is left alone, not replaced by the migrated one");
    }

    /// <summary>
    /// The shape the documentation describes as the original one: a shared password slot and no
    /// per-user rows at all. The migration invents the admin on the first unlock.
    /// </summary>
    [Fact]
    public async Task ALegacyVaultWithNoUsersAtAll_IsInitialized_AndUnlocksWithItsPassword()
    {
        var (factory, init, session) = await BuildLegacyVaultAsync(keepUsers: false);

        (await init.IsInitializedAsync()).Should().BeTrue();

        (await session.UnlockAsync(Password)).Should().BeTrue();
        var slots = await SlotsAsync(factory);
        slots.Should().ContainSingle();
        slots[0].SlotType.Should().Be("user");
        var admin = (await UsersAsync(factory)).Should().ContainSingle().Subject;
        admin.Slot.Should().Be(slots[0].SlotId, "a synthetic admin was created for the promoted slot");
    }

    /// <summary>
    /// Defence in depth behind the recognition above: whatever <c>IsInitializedAsync</c> answers
    /// about a database's SHAPE, a setup path must not write a new identity and a new master DEK
    /// into a database that already carries either. R2's live mixed-version test (U2c) found
    /// /api/init/standalone succeeding on a legacy vault, leaving a SECOND identity row and a
    /// setupadmin whose DEK is the only one the node knows — the operator's data still there, still
    /// sealed under the old key, and now unreachable.
    /// </summary>
    [Fact]
    public async Task InitializingOverADatabaseThatAlreadyHoldsANode_IsRefused()
    {
        var (_, init, _) = await BuildLegacyVaultAsync(keepUsers: true);

        (await init.IsInitializedAsync()).Should().BeTrue("the vault is intact and recognizable");
        (await init.IsClaimedAsync()).Should().BeTrue("it carries an identity row and a key slot");

        var act = () => init.InitializeAsync("setupadmin", "Fresh setup", "another-password-1");

        await act.Should().ThrowAsync<InvalidOperationException>().WithMessage("*already*");
    }

    /// <summary>
    /// The same guard where the shape reads as incomplete: while a restore bootstrap is in progress
    /// the node answers "not initialized" (on purpose — the restore may finish it) and must still
    /// not be initialized over, or the half-written row and the new one would both claim to be this
    /// node, and the new master DEK would be the only one the node knows.
    /// </summary>
    [Fact]
    public async Task InitializingOverAnIdentityRowMidRestore_IsAlsoRefused()
    {
        var (factory, init, _) = await BuildLegacyVaultAsync(keepUsers: true);
        using (var conn = factory.CreateConnection())
        {
            await conn.ExecuteAsync("DELETE FROM tbl_key_slot");
            await conn.ExecuteAsync("DELETE FROM tbl_user");
            await conn.ExecuteAsync("UPDATE tbl_node_identity SET sentinel_value = NULL");
        }
        await new RestoreBootstrapMarker(factory).SetAsync();

        (await init.IsInitializedAsync()).Should().BeFalse("a bootstrap is in progress — restore may finish it");
        (await init.IsClaimedAsync()).Should().BeTrue("but the identity row is still somebody's");

        var act = () => init.InitializeAsync("setupadmin", "Fresh setup", "another-password-1");

        await act.Should().ThrowAsync<InvalidOperationException>().WithMessage("*already holds a node*");
    }

    /// <summary>
    /// The real 1.0.11 vault, from the rehearsal on a copy of the owner's server (review release-a2
    /// batch 2): an identity row, and <c>sentinel_value</c> NULL — the sentinel only became part of
    /// the vault later, and 1.0.11 neither writes nor requires one. Such a vault is initialized and
    /// unlocks with its password (a missing sentinel is nothing to verify a slot against, not a
    /// refusal), so any test that asks for the sentinel on top of the row reads a working vault as
    /// an empty one and points its operator at the setup wizard.
    /// </summary>
    [Fact]
    public async Task AVaultWithANullSentinel_IsInitialized_AndUnlocksWithItsPassword()
    {
        var (factory, init, session) = await BuildLegacyVaultAsync(keepUsers: true);
        using (var conn = factory.CreateConnection())
            await conn.ExecuteAsync("UPDATE tbl_node_identity SET sentinel_value = NULL");

        (await init.IsInitializedAsync()).Should().BeTrue("1.0.11 answered true here, and this is its vault");

        (await session.UnlockAsync(Password)).Should().BeTrue(
            "the vault opens with the password it was made with; the sentinel is not a gate");
        session.IsUnlocked.Should().BeTrue();
    }

    /// <summary>
    /// The one shape that IS "not initialized" while an identity row exists: a restore bootstrap in
    /// progress. The bootstrap writes the identity row first and the slot, the admin and the
    /// sentinel after it, so a crash in between leaves a node that cannot be unlocked — the
    /// operator's next move is to restore again, and the flag has to say so for that retry to be
    /// allowed in (the retry then resumes rather than repeats; RecoveryRestoreService).
    /// </summary>
    [Fact]
    public async Task ANodeWithARestoreBootstrapInProgress_IsNotInitialized()
    {
        var (factory, init, _) = await BuildLegacyVaultAsync(keepUsers: true);
        var marker = new RestoreBootstrapMarker(factory);

        (await marker.IsSetAsync()).Should().BeFalse("nothing is being restored in this test");
        (await init.IsInitializedAsync()).Should().BeTrue("and the node is a node");

        await marker.SetAsync();

        (await marker.IsSetAsync()).Should().BeTrue();
        (await init.IsInitializedAsync()).Should().BeFalse(
            "half a bootstrap is not an initialized node: the restore that would finish it must be allowed to run");

        // Lowered the way the restore lowers it — with the write that completes the bootstrap.
        using (var conn = factory.CreateConnection())
        using (var tx = conn.BeginTransaction())
        {
            RestoreBootstrapMarker.Clear(conn, tx);
            tx.Commit();
        }
        (await init.IsInitializedAsync()).Should().BeTrue("the bootstrap finished: the node is a node again");
    }
}