using BeeMemoryBank.Core.Interfaces;
using BeeMemoryBank.Core.Models;
using BeeMemoryBank.Core.Services;
using BeeMemoryBank.Storage.Sqlite;
using Dapper;
using Microsoft.Extensions.DependencyInjection;

namespace BeeMemoryBank.Core.Tests;

/// <summary>
/// A vault from before the password unification, opened by this build (docs/encryption.md,
/// "Password Unification"): one shared <c>slot_type='password'</c> row, no user pointing at a slot
/// until the first successful unlock runs <see cref="LegacyPasswordSlotMigrationService"/>.
///
/// <para>This is the 1.0.11 upgrade path, and it is not a hypothetical: the vault is intact and one
/// password away from being usable. <c>IsInitializedAsync</c> answering "not initialized" here sends
/// the operator to the setup wizard instead of the unlock prompt, so the unlock that would migrate
/// the shape never happens — the brick the reviewers found in release-a2 (agy#2, sec#5).</para>
///
/// <para>The fixtures are built rather than shipped as a binary: a modern vault is stood up and then
/// rewritten into the legacy shape by the same rules the migration service reads it by (its slot
/// type constant), with a sanity check that the rewrite really did change the shape. A vault made by
/// the real 1.0.11 binaries is verified separately in REPORT.md — a committed binary fixture would
/// age badly and cannot be regenerated by CI.</para>
/// </summary>
public class LegacyVaultUpgradeTests : IAsyncDisposable
{
    private const string Password = "legacy-vault-pass-1";
    private readonly string _root = Path.Combine(Path.GetTempPath(), "bmb-legacy-" + Guid.NewGuid().ToString("N"));
    private DbConnectionFactory? _factory;
    private readonly List<ServiceProvider> _providers = [];

    public async ValueTask DisposeAsync()
    {
        foreach (var p in _providers)
        {
            try { p.Dispose(); } catch { }
        }
        try { _factory?.Dispose(); } catch { }
        try { Directory.Delete(_root, recursive: true); } catch { }
        await ValueTask.CompletedTask;
    }

    /// <summary>
    /// A vault as this build initializes one, then rewritten into the pre-unification shape:
    /// the slot becomes the shared legacy one, no user points at a slot, and the unification marker
    /// is gone (a pre-unification vault never had one).
    /// </summary>
    private async Task<(DbConnectionFactory Factory, InitializationService Init, SessionService Session)>
        BuildLegacyVaultAsync(bool keepUsers)
    {
        // The Guid/DateTime handlers every repository read relies on (DapperConfig).
        DapperConfig.Configure();
        Directory.CreateDirectory(_root);
        var factory = new DbConnectionFactory(_root);
        _factory = factory;
        await new MigrationRunner(factory).RunMigrationsAsync();

        var keySlots = new KeySlotRepository(factory);
        var nodeRepo = new NodeIdentityRepository(factory);
        var userRepo = new UserRepository(factory);
        var init = new InitializationService(nodeRepo, keySlots, userRepo, factory);
        await init.InitializeAsync("admin", "LegacyNode", Password);

        // Sanity: the vault this build makes is the modern shape, so what follows is a real change.
        (await init.IsInitializedAsync()).Should().BeTrue("the vault was just initialized");
        (await keySlots.GetAllAsync()).Should().ContainSingle(s => s.SlotType == "user");

        using (var conn = factory.CreateConnection())
        {
            await conn.ExecuteAsync(
                "UPDATE tbl_key_slot SET slot_type = @legacy",
                new { legacy = LegacyPasswordSlotMigrationService.LegacySlotType });
            await conn.ExecuteAsync("UPDATE tbl_user SET key_slot_id = NULL");
            await conn.ExecuteAsync("DELETE FROM tbl_migration_marker WHERE key = 'legacy_password_unified'");
            if (!keepUsers)
                await conn.ExecuteAsync("DELETE FROM tbl_user");
        }

        // The migration runs from inside UnlockAsync through the DI scope factory — the same way
        // the host wires it (SessionService's optional scopeFactory parameter) — so the test
        // exercises the real upgrade path, not a hand-called migration.
        var services = new ServiceCollection();
        services.AddSingleton<IKeySlotRepository>(keySlots);
        services.AddSingleton<IUserRepository>(userRepo);
        services.AddSingleton<IDbConnectionFactory>(factory);
        // TryDeriveAuthorizedMasterDekAsync resolves the identity (for the v=0/v=1 seed path) and
        // the retired-DEK store while it walks the slots.
        services.AddSingleton<INodeIdentityRepository>(nodeRepo);
        services.AddSingleton<IRetiredMasterDekStore>(new RetiredMasterDekStore(factory));
        services.AddTransient<LegacyPasswordSlotMigrationService>();
        var provider = services.BuildServiceProvider();
        _providers.Add(provider);

        var session = new SessionService(keySlots, provider.GetRequiredService<IServiceScopeFactory>());
        return (factory, init, session);
    }

    private async Task<List<MasterKeyStore>> SlotsAsync(DbConnectionFactory factory)
    {
        using var conn = factory.CreateConnection();
        return (await conn.QueryAsync<MasterKeyStore>(
            "SELECT slot_id AS SlotId, slot_type AS SlotType FROM tbl_key_slot")).ToList();
    }

    private async Task<List<(string Username, string Role, int? Slot)>> UsersAsync(DbConnectionFactory factory)
    {
        using var conn = factory.CreateConnection();
        var rows = await conn.QueryAsync<(string Username, string Role, int? Slot)>(
            "SELECT username AS Username, role AS Role, key_slot_id AS Slot FROM tbl_user WHERE is_active = 1");
        return rows.ToList();
    }

    [Fact]
    public async Task ALegacyVaultWhoseUsersHaveNoSlot_IsInitialized_AndUnlocksWithItsPassword()
    {
        var (factory, init, session) = await BuildLegacyVaultAsync(keepUsers: true);

        (await init.IsInitializedAsync()).Should().BeTrue(
            "the vault is intact: the operator's next stop is the unlock prompt, not the setup wizard");

        (await session.UnlockAsync(Password)).Should().BeTrue("the old password still opens the vault");
        session.IsUnlocked.Should().BeTrue();

        // The unlock ran the migration: the shared slot is promoted to a per-user one, and a
        // superadmin owns it. The migration cannot know WHOSE password opened the vault, so it
        // creates its own admin for the promoted slot; the pre-existing user stays and is
        // provisioned with a slot of their own at their next login (UserService.TryAssignKeySlotAsync),
        // which is why this asserts an owner rather than naming one.
        var slots = await SlotsAsync(factory);
        slots.Should().ContainSingle("the shared slot is promoted, not duplicated");
        slots[0].SlotType.Should().Be("user");
        var owners = (await UsersAsync(factory)).Where(u => u.Slot == slots[0].SlotId).ToList();
        owners.Should().ContainSingle("the promoted slot belongs to exactly one account");
        owners[0].Role.Should().Be("superadmin");
        (await UsersAsync(factory)).Should().Contain(u => u.Username == "admin",
            "the pre-existing user is left alone, not replaced by the migrated one");
    }

    /// <summary>
    /// The shape the documentation describes as the original one: a shared password slot and no
    /// per-user rows at all. The migration invents the admin on the first unlock.
    /// </summary>
    [Fact]
    public async Task ALegacyVaultWithNoUsersAtAll_IsInitialized_AndUnlocksWithItsPassword()
    {
        var (factory, init, session) = await BuildLegacyVaultAsync(keepUsers: false);

        (await init.IsInitializedAsync()).Should().BeTrue();

        (await session.UnlockAsync(Password)).Should().BeTrue();
        var slots = await SlotsAsync(factory);
        slots.Should().ContainSingle();
        slots[0].SlotType.Should().Be("user");
        var admin = (await UsersAsync(factory)).Should().ContainSingle().Subject;
        admin.Slot.Should().Be(slots[0].SlotId, "a synthetic admin was created for the promoted slot");
    }

    /// <summary>
    /// And the shape DK1-2's rule exists for stays a brick of the other kind: an identity row with
    /// nothing behind it — no slot, no sentinel, no user — is not an initialized node, so the restore
    /// that would finish it is allowed to run.
    /// </summary>
    [Fact]
    public async Task AnIdentityRowWithNothingBehindIt_IsStillNotInitialized()
    {
        var (factory, init, _) = await BuildLegacyVaultAsync(keepUsers: true);
        using (var conn = factory.CreateConnection())
        {
            await conn.ExecuteAsync("DELETE FROM tbl_key_slot");
            await conn.ExecuteAsync("UPDATE tbl_node_identity SET sentinel_value = NULL");
        }

        (await init.IsInitializedAsync()).Should().BeFalse(
            "nothing can open this vault, and it must not be mistaken for one that can");
    }
}