using System.Text.Json;
using System.Text.Json.Serialization;

namespace BeeMemoryBank.Api.Services.BlindBackup;

/// <summary>
/// Where restic keeps the repository: a plain folder on some mounted volume, or an S3-compatible
/// bucket (MinIO, B2, Hetzner). An S3 repository MUST carry a key prefix — the recovery-set is
/// written as a sibling object of that prefix, outside the repository's own tree (plan §6.8), and
/// a repository sitting at the bucket root has no outside to be written to.
/// </summary>
public enum BlindRepoType
{
    Folder,
    S3,
}

/// <summary>Values of <see cref="BlindBackupSettings.ResticPasswordSource"/>.</summary>
public static class ResticPasswordSources
{
    /// <summary>Copied from the console password (the default; follows it until a repository exists).</summary>
    public const string Console = "console";

    /// <summary>Entered by the operator (console form, <c>bmb blind init</c>): wins over the default for good.</summary>
    public const string Explicit = "explicit";
}

/// <summary>
/// Local, non-replicated settings of a blind node's backup subsystem (plan §7): where the restic
/// repository is, how long snapshots are kept, when backups run, how much CPU they may use.
///
/// <para>Deliberately a JSON file (<c>{dataPath}/blind/settings.json</c>) and NOT a vault table:
/// a reseed replaces the whole vault database (plan §5.2), and a blind node that came back up
/// from a reseed with its backup configuration gone would silently stop backing up — the one
/// failure the whole feature exists to prevent. The restic password is stored in the clear here
/// on purpose (plan §7: "in the clear on the blind node"); the file is created 0600 on Linux.</para>
/// </summary>
public sealed partial class BlindBackupSettings
{
    [System.Text.RegularExpressions.GeneratedRegex(@"^[0-9]+(B|KiB|MiB|GiB|TiB)?$")]
    private static partial System.Text.RegularExpressions.Regex GoMemLimitFormat();

    public BlindRepoType RepoType { get; set; } = BlindRepoType.Folder;

    /// <summary>Folder repository: absolute path, e.g. /backups/bmb-blind. Docker volume mount in practice.</summary>
    public string? RepoFolder { get; set; }

    /// <summary>S3: https endpoint WITHOUT the bucket, e.g. https://minio.lan:9000.</summary>
    public string? S3Endpoint { get; set; }
    /// <summary>S3 bucket name.</summary>
    public string? S3Bucket { get; set; }
    /// <summary>Key prefix the repository lives under, e.g. "blind-repo". Required — see <see cref="BlindRepoType"/>.</summary>
    public string? S3Prefix { get; set; }
    public string? S3AccessKey { get; set; }
    public string? S3SecretKey { get; set; }
    /// <summary>S3 region for request signing; any value works on MinIO/B2/Hetzner.</summary>
    public string? S3Region { get; set; } = "us-east-1";

    /// <summary>
    /// The restic repository password. Generated by the Windows node during pairing and delivered
    /// by the seed flow (plan §4.2); until that flow exists it is accepted as a local console/CLI
    /// setting so the backup subsystem is testable end to end.
    /// </summary>
    public string? ResticPassword { get; set; }

    /// <summary>
    /// Where <see cref="ResticPassword"/> came from (<see cref="ResticPasswordSources"/>). <c>null</c>
    /// on a file written before this field existed: a password found there is somebody's own choice
    /// and is never touched by a console password change.
    /// </summary>
    public string? ResticPasswordSource { get; set; }

    /// <summary>
    /// The repository (<see cref="RepositoryKey"/>) a backup found or created. From then on it is
    /// encrypted under <see cref="ResticPassword"/>: the console password must not move it and the
    /// settings refuse another one (a repository is not re-encrypted here). Tied to the location, so
    /// pointing the backup at another repository starts over. <see cref="BlindBackupSettingsStore.Save"/>
    /// keeps it, so a write that read the file before the first backup cannot drop it.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? RepoInUseKey { get; set; }

    /// <summary>
    /// What the first build of this feature wrote: "in use at whatever location is configured".
    /// Read into <see cref="RepoInUseKey"/> and never written again; the settings GET also fills it, for the form.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool RepoInUse { get; set; }

    /// <summary>
    /// A non-folder (S3) repository was configured once. This node cannot look inside a bucket, so from
    /// then on a repository may exist and the console password is never taken as the restic password.
    /// Sticky, like <see cref="RepoInUseKey"/>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool RemoteRepoSeen { get; set; }

    // Standard retention (plan §7), each overridable.
    public int KeepDaily { get; set; } = 7;
    public int KeepWeekly { get; set; } = 4;
    public int KeepMonthly { get; set; } = 12;
    public int KeepYearly { get; set; } = 3;

    /// <summary>Daily backup time ("HH:mm"). Interpreted as UTC — containers run UTC by default.</summary>
    public string ScheduleTime { get; set; } = "03:00";

    /// <summary>
    /// The daily schedule. <c>null</c> means nobody has decided — the console toggle has never been
    /// flipped, <c>bmb blind init</c> never said, and the file has no <c>scheduleEnabled</c> key —
    /// and an undecided schedule runs as soon as the node can back up at all
    /// (<see cref="ScheduleRuns"/>). That is the release-A default: a node with a repository backs
    /// up without the operator having to find a second switch. <c>true</c>/<c>false</c> is the
    /// operator's own answer (console toggle, a hand-edited settings file) and the default never
    /// overrides it.
    /// </summary>
    public bool? ScheduleEnabled { get; set; }

    /// <summary>
    /// What the operator (or the default) wants, whether or not the node can do it yet: used to
    /// decide how strictly a settings write is checked. An explicit "on" over an incomplete
    /// configuration must be refused rather than stored as a promise the node will not keep; a
    /// node that is simply not configured yet has asked for nothing and may be saved in pieces.
    /// </summary>
    public bool ScheduleWanted => ScheduleEnabled ?? true;

    /// <summary>
    /// Whether the schedule actually runs: wanted, and possible — a configured repository with its
    /// password (<see cref="Validate"/>). This is the one the scheduler asks.
    /// </summary>
    public bool ScheduleRuns(string nodeDataPath) => ScheduleWanted && Validate(nodeDataPath).Ok;

    /// <summary>
    /// Whether a settings write is checked by the strict rule (<see cref="Validate"/>) rather than
    /// the draft rule (<see cref="ValidateValues"/>): a schedule that runs must not be broken by a
    /// partial update, and an explicit "on" must not be saved over a configuration that cannot run
    /// it. An off schedule over an incomplete draft is the only case the draft rule is for.
    /// </summary>
    public bool ScheduleGuarded(string nodeDataPath) => ScheduleEnabled ?? ScheduleRuns(nodeDataPath);
    /// <summary>restic check --read-data-subset percentage on the weekly schedule.</summary>
    public int CheckSubsetPercent { get; set; } = 5;

    /// <summary>Go soft memory limit for restic (GOMEMLIMIT), e.g. "512MiB".</summary>
    public string ResticGoMemLimit { get; set; } = "512MiB";

    /// <summary>
    /// Override for the restic binary; default "restic" from PATH (the Docker image installs it).
    /// Only settable by editing the settings file on the node, never through the Api.
    /// </summary>
    public string? ResticBinary { get; set; }

    internal static readonly JsonSerializerOptions JsonOpts = new()
    {
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    /// <summary>
    /// Everything a backup needs is configured AND well-formed (<see cref="ValidateValues"/>).
    /// Required to run a job and whenever the stored settings have the schedule enabled. The
    /// message names the first problem.
    /// </summary>
    public (bool Ok, string? Problem) Validate(string nodeDataPath)
    {
        if (string.IsNullOrWhiteSpace(ResticPassword))
            return (false, "restic repository password is not set");
        if (RepoType == BlindRepoType.Folder)
        {
            if (string.IsNullOrWhiteSpace(RepoFolder))
                return (false, "repository folder is not set");
        }
        else
        {
            if (string.IsNullOrWhiteSpace(S3Endpoint))
                return (false, "S3 endpoint must be an absolute http(s) URL");
            if (string.IsNullOrWhiteSpace(S3Bucket))
                return (false, "S3 bucket is not set");
            if (string.IsNullOrWhiteSpace(S3Prefix))
                return (false, "S3 repository needs a key prefix (the recovery-set is written next to it, outside the repository tree)");
            if (string.IsNullOrWhiteSpace(S3AccessKey) || string.IsNullOrWhiteSpace(S3SecretKey))
                return (false, "S3 credentials are not set");
        }
        return ValidateValues(nodeDataPath);
    }

    /// <summary>
    /// Every value that IS set is acceptable — the check for a draft: configuration arrives in
    /// pieces (the repository first, the password later from the pairing flow), so a missing
    /// piece is fine here, a wrong one is not.
    /// </summary>
    public (bool Ok, string? Problem) ValidateValues(string nodeDataPath)
    {
        if (RepoType == BlindRepoType.Folder && !string.IsNullOrWhiteSpace(RepoFolder)
            && BlindPaths.OutsideNodeData(RepoFolder, nodeDataPath, "repository folder") is { } location)
            return (false, location);
        if (!string.IsNullOrWhiteSpace(S3Endpoint)
            && (!Uri.TryCreate(S3Endpoint, UriKind.Absolute, out var uri)
                || (uri.Scheme != Uri.UriSchemeHttp && uri.Scheme != Uri.UriSchemeHttps)))
            return (false, "S3 endpoint must be an absolute http(s) URL");
        if (KeepDaily < 0 || KeepWeekly < 0 || KeepMonthly < 0 || KeepYearly < 0)
            return (false, "retention counts cannot be negative");
        if (CheckSubsetPercent is < 1 or > 100)
            return (false, "check subset percent must be between 1 and 100");
        if (!TimeSpan.TryParse(ScheduleTime, out _))
            return (false, "schedule time must be HH:mm");
        // restic's Go runtime refuses to start on a malformed GOMEMLIMIT — every backup would
        // fail at launch, so a typo is caught here, where the operator is looking.
        if (!GoMemLimitFormat().IsMatch(ResticGoMemLimit ?? ""))
            return (false, "restic memory limit must look like 512MiB or 1GiB");
        return (true, null);
    }

    /// <summary>Names the repository these settings point at: what <see cref="RepoInUseKey"/> is about.</summary>
    public string RepositoryKey() => RepoType == BlindRepoType.Folder
        ? "folder:" + (string.IsNullOrWhiteSpace(RepoFolder) ? "" : Path.GetFullPath(RepoFolder))
        : $"s3:{S3Endpoint?.TrimEnd('/')}/{S3Bucket}/{S3Prefix}";

    /// <summary>A backup has used the repository these settings point at (its password is fixed).</summary>
    public bool RepositoryInUse() => RepoInUseKey == RepositoryKey();

    /// <summary>
    /// Whether a repository may already exist, so the console password must not become the restic
    /// password: a backup has used it, a folder repository has its <c>config</c> file, or a remote
    /// repository was ever configured (this node cannot look inside a bucket).
    /// </summary>
    public bool RepositoryExists() =>
        RepositoryInUse() || RepoType != BlindRepoType.Folder || RemoteRepoSeen
        || (!string.IsNullOrWhiteSpace(RepoFolder) && File.Exists(Path.Combine(RepoFolder, "config")));

    /// <summary>The RESTIC_REPOSITORY value for the configured repository. Only valid after <see cref="Validate"/> passed.</summary>
    public string ResticRepository() => RepoType == BlindRepoType.Folder
        ? Path.GetFullPath(RepoFolder!)
        : $"s3:{S3Endpoint!.TrimEnd('/')}/{S3Bucket}/{S3Prefix}";
}
