"""blind-link: keeps the linked-source lists of the blind projects in step with the sources they link.

The blind node does not copy code. The blind host LINKS the original Api source files a blind node needs (same types, same
namespaces, one definition):

  server/BeeMemoryBank.BlindNode  links files of server/BeeMemoryBank.Api                               -> linked-api-files.props

Since the vault split (BMB-99, 2.0.1) the host references the shared libraries (Core, Storage, Sync, Crypto, Search) directly, so
there is no library half any more: the former libs/BeeMemoryBank.Blind link assembly and the phone proxy are gone, and the library
code a blind node must not contain is not in those libraries at all (it is libs/BeeMemoryBank.Vault).

This tool finds the Api set by compiling: start from the seed list, build the host, read the "type or name not found"
errors, link the Api file that declares each missing name, build again, until the build is clean. The result is written to the
.props file, which is checked in, so a normal build never needs this tool - it is for recomputing the set when a
seed or a source file changes.

Usage:  python tools/blind-link/blind_link.py [--check]
  (no flag)  recompute and rewrite the props files
  --check    recompute and fail (exit 1) when the checked-in props differ (the props are restored afterwards)

Lists (paths relative to the repo root):
  seeds.txt    one path or prefix per line; `api:` before a path means relative to server/BeeMemoryBank.Api
  exclude.txt  same syntax; a file on it is never linked - if the closure needs one, the build fails and the host gets
               a replacement instead (that is the point: what is not linked cannot be in the container)
A trailing `*` is a prefix match, a path without it matches the file or a directory.

Nothing here modifies a source file. The blind composition is BlindNodeServices (host) over the shared AddNode* modules.
"""
import collections
import io
import os
import re
import subprocess
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
API = os.path.join(REPO, 'server', 'BeeMemoryBank.Api')
HOST_DIR = os.path.join(REPO, 'server', 'BeeMemoryBank.BlindNode')
HOST_PROJ = os.path.join(HOST_DIR, 'BeeMemoryBank.BlindNode.csproj')
HOST_PROPS = os.path.join(HOST_DIR, 'linked-api-files.props')
SEEDS_FILE = os.path.join(os.path.dirname(__file__), 'seeds.txt')
EXCLUDE_FILE = os.path.join(os.path.dirname(__file__), 'exclude.txt')
WIRING = re.compile(r'(^|/)(ApiServices|ApiStartupTasks)\.cs$')   # the Api's composition roots register the whole application

TYPE_RE = re.compile(r'\b(?:class|record|struct|interface|enum|delegate)\s+(?:class\s+|struct\s+)?([A-Z][A-Za-z0-9_]*)')
EXT_RE = re.compile(r'static\s+[\w<>\[\],\s\?\.]+?\s+([A-Z][A-Za-z0-9_]*)\s*(?:<[^>]*>)?\s*\(\s*this\s')
PART_RE = re.compile(r'partial\s+(?:class|record|struct|interface)\s+([A-Z][A-Za-z0-9_]*)')
NAME_RES = [re.compile(r"type or namespace name '([A-Za-z0-9_]+)'"), re.compile(r"The name '([A-Za-z0-9_]+)' does not exist"),
            re.compile(r"does not contain a definition for '([A-Za-z0-9_]+)'"),
            re.compile(r"'([A-Za-z0-9_]+)' does not exist in the namespace")]
NS_RE = re.compile(r'^\s*namespace\s+([\w.]+)', re.M)
ERR_FILE_RE = re.compile(r'^(.*?)\((\d+),\d+\): error')


def read_list(path):
    out = []
    for line in io.open(path, encoding='utf-8').read().splitlines():
        line = line.split('#', 1)[0].strip()
        if line:
            out.append(line.replace('\\', '/'))
    return out


def to_repo_path(entry):
    return ('server/BeeMemoryBank.Api/' + entry[4:]) if entry.startswith('api:') else entry


def matches(rel, patterns):
    for p in patterns:
        if p.endswith('*'):
            if rel.startswith(p[:-1]):
                return True
        elif rel == p or rel.startswith(p.rstrip('/') + '/'):
            return True
    return False


def source_files():
    out = []
    roots = [(API, 'server/BeeMemoryBank.Api')]
    for root, prefix in roots:
        for r, d, fs in os.walk(root):
            d[:] = [x for x in d if x not in ('bin', 'obj', 'data', 'Properties')]
            for f in fs:
                if f.endswith('.cs') and not f.endswith('.g.cs') and f not in ('Program.cs', 'AssemblyInfo.cs'):
                    out.append(prefix + '/' + os.path.relpath(os.path.join(r, f), root).replace('\\', '/'))
    return sorted(out)


def props_text(files, project_dir):
    lines = ['<Project>', '  <!-- GENERATED by tools/blind-link/blind_link.py - do not edit by hand. -->', '  <ItemGroup>']
    for f in sorted(files):
        full = os.path.join(REPO, f.replace('/', os.sep))
        rel = os.path.relpath(full, project_dir).replace('/', '\\')
        link = f.replace('server/BeeMemoryBank.Api/', 'Api/').replace('/', '\\')
        lines.append('    <Compile Include="%s" Link="%s" />' % (rel, link))
    lines += ['  </ItemGroup>', '</Project>', '']
    return '\r\n'.join(lines)


def write(path, text):
    io.open(path, 'w', encoding='utf-8', newline='').write(text)


def props_by_path(links):
    return {HOST_PROPS: props_text([f for f in links if f.startswith('server/')], HOST_DIR)}


def write_props(links):
    for path, text in props_by_path(links).items():
        write(path, text)


def main():
    check = '--check' in sys.argv
    before = {p: io.open(p, encoding='utf-8', newline='').read() for p in (HOST_PROPS,) if os.path.exists(p)}
    files = source_files()
    provided = set()
    seeds = [to_repo_path(s) for s in read_list(SEEDS_FILE)]
    exclude = [to_repo_path(s) for s in read_list(EXCLUDE_FILE)]
    text, declared, partial = {}, collections.defaultdict(set), collections.defaultdict(set)
    ns_files = collections.defaultdict(set)     # namespace -> files that declare it
    for f in files:
        s = re.sub(r'//[^\n]*', '', io.open(os.path.join(REPO, f.replace('/', os.sep)), encoding='utf-8', errors='replace').read())
        text[f] = s
        for n in set(TYPE_RE.findall(s)) | set(EXT_RE.findall(s)):
            declared[n].add(f)
        for n in PART_RE.findall(s):
            partial[n].add(f)
        for ns in NS_RE.findall(s):
            ns_files[ns].add(f)
    ok = lambda f: not matches(f, exclude) and not WIRING.search(f) and f not in provided
    links = {f for f in files if matches(f, seeds) and ok(f)}
    unresolved = collections.Counter()
    ns_added = set()   # files linked only so that a namespace exists
    errs = []

    def build():
        write_props(links)
        p = subprocess.run(['dotnet', 'build', HOST_PROJ, '-c', 'Release', '--no-incremental', '-nologo', '-v', 'q', '-clp:NoSummary'],
                           capture_output=True, text=True, encoding='utf-8', errors='replace')
        return sorted(set(l.strip() for l in (p.stdout + p.stderr).splitlines() if ' error ' in l))

    for it in range(1, 80):
        errs = build()
        print('iteration %d: %d api files linked, %d distinct errors' % (
            it, sum(1 for f in links if f.startswith('server/')), len(errs)), flush=True)
        wanted = collections.Counter()   # (name, from_lib_project: always False now, kept for the shape of the loop)
        for l in errs:
            m = ERR_FILE_RE.match(l)
            from_lib = False
            for rx in NAME_RES:
                mm = rx.search(l)
                if mm:
                    wanted[(mm.group(1), from_lib)] += 1
                    break
        added = 0
        for (name, from_lib), _ in wanted.items():
            cands = {c for c in declared.get(name, set()) if ok(c)}
            if not cands:   # not a type: a namespace the code names in a using (Core.Exceptions, Core.Embeddings ...)
                # One file is enough for the namespace to exist; the types in it are linked one by one, as they are used.
                for ns, nfs in ns_files.items():
                    if ns.endswith('.' + name):
                        usable = sorted((c for c in nfs if ok(c)), key=lambda c: len(text[c]))
                        if usable and not any(c in links for c in usable):
                            cands.add(usable[0])
                if cands:
                    for c in cands:
                        if c not in links:
                            links.add(c)
                            ns_added.add(c)
                            added += 1
                    continue
            if from_lib:
                cands = {c for c in cands if c.startswith('libs/')} or cands
            else:
                api_c = {c for c in cands if c.startswith('server/')}
                cands = api_c or cands
            if not cands:
                unresolved[name] += 1
                continue
            if len(cands) > 1 and not all(name in PART_RE.findall(text[c]) for c in cands):
                unresolved['%s (ambiguous: %s)' % (name, ', '.join(sorted(cands)))] += 1
                continue
            for c in cands:
                if c not in links:
                    links.add(c)
                    added += 1
        # Deliberately NO 'interface -> every implementing class' rule: the compiler cannot tell which implementation a container
        # picks, so such a rule linked classes nothing names (Codex review B). The compositions (BlindComposition, BlindNodeServices,
        # BlindMobileServices) name every implementation they register; hosted services nothing names are listed in seeds.txt.
        for f in list(links):   # a partial class is linked whole or not at all
            for n in PART_RE.findall(text[f]):
                for other in partial[n]:
                    if other not in links and ok(other):
                        links.add(other)
                        added += 1
        if added == 0:
            break
    # A namespace stand-in is the first file found for it, before the real users of that namespace were linked, so it can be an
    # orphan nothing names. Try each one out: keep it only if the build breaks without it.
    for c in sorted(ns_added & links):
        links.discard(c)
        if build():
            links.add(c)
        else:
            print('pruned (nothing needs it): %s' % c, flush=True)
    errs = build()
    n_api = sum(1 for f in links if f.startswith('server/'))
    print('DONE: %d Api files linked; remaining errors: %d' % (n_api, len(errs)))
    for e in errs[:40]:
        print('  ' + e[:260])
    if unresolved:
        print('unresolved names: %s' % dict(unresolved))
    after = props_by_path(links)
    if check:
        same = all(before.get(p) == t for p, t in after.items())
        print('props match the checked-in files' if same else 'props DIFFER from the checked-in files')
        for p, t in before.items():
            write(p, t)
        return 0 if (same and not errs) else 1
    return 1 if errs else 0


if __name__ == '__main__':
    sys.exit(main())
