"""blind-link: keeps server/BeeMemoryBank.BlindNode/linked-api-files.props in step with the Api sources.

The BlindNode host does not copy Api code: it LINKS the Api source files a blind node needs (same types, same
namespaces, one definition). This tool finds that set by compiling: starting from the seed list it builds the
project, reads the "type or name not found" errors, links the Api file that declares each missing name and builds
again, until the build is clean. The result is written to linked-api-files.props, which is checked in, so a normal
build never needs this tool - it is for (re)computing the set when a seed or an Api file changes.

Usage:  python tools/blind-link/blind_link.py [--check]
  (no flag)  recompute and rewrite linked-api-files.props
  --check    recompute into memory and fail (exit 1) when the checked-in props differ

Nothing here modifies Api sources. Excluded names (EXCLUDE) are never linked: they are the full-node features a
blind node must not contain (MCP, agent auth, caller scope, chat, embeddings, media, update, DEK rotation...).
"""
import collections
import io
import os
import re
import subprocess
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
API = os.path.join(REPO, 'server', 'BeeMemoryBank.Api')
PROJ_DIR = os.path.join(REPO, 'server', 'BeeMemoryBank.BlindNode')
PROJ = os.path.join(PROJ_DIR, 'BeeMemoryBank.BlindNode.csproj')
PROPS = os.path.join(PROJ_DIR, 'linked-api-files.props')
SEEDS_FILE = os.path.join(os.path.dirname(__file__), 'seeds.txt')
EXCLUDE_FILE = os.path.join(os.path.dirname(__file__), 'exclude.txt')


def read_list(path):
    out = []
    for line in io.open(path, encoding='utf-8').read().splitlines():
        line = line.split('#', 1)[0].strip()
        if line:
            out.append(line.replace('\\', '/'))
    return out


def api_files():
    out = []
    for r, d, fs in os.walk(API):
        d[:] = [x for x in d if x not in ('bin', 'obj', 'data', 'Properties')]
        for f in fs:
            if f.endswith('.cs') and not f.endswith('.g.cs') and f != 'Program.cs':
                out.append(os.path.relpath(os.path.join(r, f), API).replace('\\', '/'))
    return sorted(out)


TYPE_RE = re.compile(r'\b(?:class|record|struct|interface|enum|delegate)\s+(?:class\s+|struct\s+)?([A-Z][A-Za-z0-9_]*)')
EXT_RE = re.compile(r'static\s+[\w<>\[\],\s\?\.]+?\s+([A-Z][A-Za-z0-9_]*)\s*(?:<[^>]*>)?\s*\(\s*this\s')
PART_RE = re.compile(r'partial\s+(?:class|record|struct|interface)\s+([A-Z][A-Za-z0-9_]*)')
NAME_RES = [re.compile(r"type or namespace name '([A-Za-z0-9_]+)'"), re.compile(r"The name '([A-Za-z0-9_]+)' does not exist"),
            re.compile(r"does not contain a definition for '([A-Za-z0-9_]+)'"), re.compile(r"'([A-Za-z0-9_]+)' does not exist in the namespace")]


def matches(rel, patterns):
    for p in patterns:
        if rel == p or rel.startswith(p.rstrip('/') + '/') or (p.endswith('*') and rel.startswith(p[:-1])):
            return True
    return False


def write_props(links):
    lines = ['<Project>', '  <!-- GENERATED by tools/blind-link/blind_link.py - do not edit by hand. -->', '  <ItemGroup>']
    for f in sorted(links):
        w = f.replace('/', '\\')
        lines.append('    <Compile Include="..\\BeeMemoryBank.Api\\%s" Link="Api\\%s" />' % (w, w))
    lines += ['  </ItemGroup>', '</Project>', '']
    return '\r\n'.join(lines)


def main():
    check = '--check' in sys.argv
    before = io.open(PROPS, encoding='utf-8', newline='').read() if os.path.exists(PROPS) else None
    files = api_files()
    seeds = read_list(SEEDS_FILE)
    exclude = read_list(EXCLUDE_FILE)
    text, declared, partial = {}, collections.defaultdict(set), collections.defaultdict(set)
    for f in files:
        s = re.sub(r'//[^\n]*', '', io.open(os.path.join(API, f), encoding='utf-8', errors='replace').read())
        text[f] = s
        for n in set(TYPE_RE.findall(s)) | set(EXT_RE.findall(s)):
            declared[n].add(f)
        for n in PART_RE.findall(s):
            partial[n].add(f)
    links = {f for f in files if matches(f, seeds) and not matches(f, exclude)}
    unresolved = collections.Counter()
    for it in range(1, 60):
        io.open(PROPS, 'w', encoding='utf-8', newline='').write(write_props(links))
        p = subprocess.run(['dotnet', 'build', PROJ, '-c', 'Release', '--no-incremental', '-nologo', '-v', 'q', '-clp:NoSummary'],
                           capture_output=True, text=True, encoding='utf-8', errors='replace')
        errs = sorted(set(l.strip() for l in (p.stdout + p.stderr).splitlines() if ' error ' in l))
        print('iteration %d: %d linked files, %d distinct errors' % (it, len(links), len(errs)), flush=True)
        names = collections.Counter()
        for l in errs:
            for rx in NAME_RES:
                m = rx.search(l)
                if m:
                    names[m.group(1)] += 1
                    break
        added = 0
        for name in names:
            cands = {c for c in declared.get(name, set()) if not matches(c, exclude)}
            if not cands:
                unresolved[name] += 1
                continue
            if len(cands) > 1 and not all(name in PART_RE.findall(text[c]) for c in cands):
                unresolved[name + ' (ambiguous: ' + ', '.join(sorted(cands)) + ')'] += 1
                continue
            for c in cands:
                if c not in links:
                    links.add(c)
                    added += 1
        # a partial class is linked whole or not at all
        for f in list(links):
            for n in PART_RE.findall(text[f]):
                for other in partial[n]:
                    if other not in links and not matches(other, exclude):
                        links.add(other)
                        added += 1
        if added == 0:
            break
    result = write_props(links)
    print('DONE: %d Api files linked; remaining errors: %d' % (len(links), len(errs)))
    for e in errs[:40]:
        print('  ' + e[:260])
    if unresolved:
        print('unresolved names: %s' % dict(unresolved))
    if check:
        same = before == result
        print('props match the checked-in file' if same else 'props DIFFER from the checked-in file')
        if before is not None:
            io.open(PROPS, 'w', encoding='utf-8', newline='').write(before)
        return 0 if (same and not errs) else 1
    return 1 if errs else 0


if __name__ == '__main__':
    sys.exit(main())
